remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Timely"
description: "A simple time tracking application that allows you to track work hours acorss projects"
author: Benjamin Quintana
  name: "Java+Android Student"

# Do not change the following line.
  copyright: true
