remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Timely"
description: "A simple time tracking application that allows you to track work hours across projects"
author:
  name: "Benjamin Quintana"

# Do not change the following line.
  copyright: true
